#!/usr/bin/python3

"""
pyspodl - a spotify downloader using librespot
"""

from arguments import get_arguments

from downloader import Downloader
from config import Config
from utils import Utils

def main():
    arguments = get_arguments()
    config = Config(arguments.config_path)
    utils = Utils(config)

    downloader = Downloader(config, utils)

    for link in arguments.link.split(" "):
        downloader.download(link)


if __name__ == "__main__":
    main()
